// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// as_eth_date_cpp
CharacterVector as_eth_date_cpp(IntegerVector x);
RcppExport SEXP _ethDate_as_eth_date_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(as_eth_date_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// to_numeric_cpp
IntegerVector to_numeric_cpp(CharacterVector dates, std::string sep);
RcppExport SEXP _ethDate_to_numeric_cpp(SEXP datesSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    Rcpp::traits::input_parameter< std::string >::type sep(sepSEXP);
    rcpp_result_gen = Rcpp::wrap(to_numeric_cpp(dates, sep));
    return rcpp_result_gen;
END_RCPP
}
// parse_eth_date_cpp
CharacterVector parse_eth_date_cpp(CharacterVector dates, std::string sep, std::string orders);
RcppExport SEXP _ethDate_parse_eth_date_cpp(SEXP datesSEXP, SEXP sepSEXP, SEXP ordersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    Rcpp::traits::input_parameter< std::string >::type sep(sepSEXP);
    Rcpp::traits::input_parameter< std::string >::type orders(ordersSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_eth_date_cpp(dates, sep, orders));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ethDate_as_eth_date_cpp", (DL_FUNC) &_ethDate_as_eth_date_cpp, 1},
    {"_ethDate_to_numeric_cpp", (DL_FUNC) &_ethDate_to_numeric_cpp, 2},
    {"_ethDate_parse_eth_date_cpp", (DL_FUNC) &_ethDate_parse_eth_date_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ethDate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
