# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_eth_date_cpp <- function(x) {
    .Call(`_ethDate_as_eth_date_cpp`, x)
}

to_numeric_cpp <- function(dates, sep = "-") {
    .Call(`_ethDate_to_numeric_cpp`, dates, sep)
}

parse_eth_date_cpp <- function(dates, sep = "-", orders = "ymd") {
    .Call(`_ethDate_parse_eth_date_cpp`, dates, sep, orders)
}

